// Anime-style character design metadata
type CharacterDesign = {
    archetype: string;
    animeStyle: "one-piece" | "kingdom" | "jujutsu-kaisen" | "mixed";
    hairStyle: string;
    hairColor: string;
    eyeColor: string;
    skinTone: string;
    outfit: string;
    outfitColors: string[];
    accessories: string[];
    weapon?: string;
    pose: string;
    aura: string;
    distinctiveFeature: string;
};

export const CHARACTER_DESIGNS: Record<string, CharacterDesign> = {
    "romantic-traditional": {
        archetype: "Noble Knight",
        animeStyle: "kingdom",
        hairStyle: "Long flowing silver",
        hairColor: "#e8e8e8",
        eyeColor: "#ff4d6d",
        skinTone: "#ffd5cd",
        outfit: "Crimson armor with golden crest",
        outfitColors: ["#c1121f", "#ffd700", "#ffffff"],
        accessories: ["Crown", "Rose emblem"],
        weapon: "Longsword",
        pose: "Knight's stance",
        aura: "Golden radiance",
        distinctiveFeature: "Heart chest plate"
    },
    "romantic-modern": {
        archetype: "Urban Romantic",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Stylish bob",
        hairColor: "#4a4a4a",
        eyeColor: "#7b2cbf",
        skinTone: "#f8e8dc",
        outfit: "Designer suit with rose",
        outfitColors: ["#1a1a2e", "#e94b3c"],
        accessories: ["Glasses", "Watch"],
        pose: "Confident lean",
        aura: "Purple mystical",
        distinctiveFeature: "Dual-color eyes"
    },
    "romantic-casual": {
        archetype: "Wandering Poet",
        animeStyle: "one-piece",
        hairStyle: "Messy waves",
        hairColor: "#8b4513",
        eyeColor: "#fb6f92",
        skinTone: "#f5d5c0",
        outfit: "Flowing shirt",
        outfitColors: ["#f8f9fa", "#495057"],
        accessories: ["Pen", "Journal"],
        pose: "Writing",
        aura: "Cherry blossoms",
        distinctiveFeature: "Ink-stained hands"
    },
    "romantic-formal": {
        archetype: "Royal Suitor",
        animeStyle: "kingdom",
        hairStyle: "Elegant updo",
        hairColor: "#2c1810",
        eyeColor: "#800f2f",
        skinTone: "#ffe5d9",
        outfit: "Ceremonial kimono",
        outfitColors: ["#8b0000", "#ffd700"],
        accessories: ["Crown", "Fan"],
        weapon: "Ceremonial blade",
        pose: "Graceful bow",
        aura: "Royal crimson",
        distinctiveFeature: "Phoenix embroidery"
    },
    "romantic-creative": {
        archetype: "Dream Weaver",
        animeStyle: "mixed",
        hairStyle: "Rainbow gradient",
        hairColor: "#ff69b4",
        eyeColor: "#ff006e",
        skinTone: "#f0e5e5",
        outfit: "Ethereal robes",
        outfitColors: ["#e0aaff", "#ff99c8"],
        accessories: ["Star tiara", "Moon pendant"],
        weapon: "Magic brush",
        pose: "Floating",
        aura: "Rainbow sparkles",
        distinctiveFeature: "Color-changing eyes"
    },
    "romantic-stoic": {
        archetype: "Lone Warrior",
        animeStyle: "kingdom",
        hairStyle: "Short spiky",
        hairColor: "#1a1a1a",
        eyeColor: "#590d22",
        skinTone: "#d4a574",
        outfit: "Battle-worn armor",
        outfitColors: ["#2b2d42", "#d00000"],
        accessories: ["Red scarf", "Battle scars"],
        weapon: "Greatsword",
        pose: "Walking away",
        aura: "Red flames",
        distinctiveFeature: "Eye scar"
    },
    "analytical-traditional": {
        archetype: "Ancient Scholar",
        animeStyle: "kingdom",
        hairStyle: "Long white beard",
        hairColor: "#f0f0f0",
        eyeColor: "#023047",
        skinTone: "#ddc8ad",
        outfit: "Traditional robes",
        outfitColors: ["#774936", "#e8dcc4"],
        accessories: ["Glasses", "Scrolls"],
        weapon: "Magic staff",
        pose: "Studying",
        aura: "Blue wisdom",
        distinctiveFeature: "Third eye"
    },
    "analytical-modern": {
        archetype: "Tech Strategist",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Slicked silver",
        hairColor: "#c0c0c0",
        eyeColor: "#00b4d8",
        skinTone: "#f5f5f5",
        outfit: "Tactical suit",
        outfitColors: ["#0077b6", "#00f5ff"],
        accessories: ["AR visor", "Gauntlets"],
        weapon: "Energy blade",
        pose: "Analyzing data",
        aura: "Blue circuits",
        distinctiveFeature: "Cyber eye"
    },
    "analytical-casual": {
        archetype: "Detective",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Messy short",
        hairColor: "#2d2d2d",
        eyeColor: "#219ebc",
        skinTone: "#ede0d4",
        outfit: "Casual jacket",
        outfitColors: ["#6c757d", "#ffffff"],
        accessories: ["Magnifier", "Notepad"],
        pose: "Thinking",
        aura: "Gray mist",
        distinctiveFeature: "Half-closed eyes"
    },
    "analytical-formal": {
        archetype: "Grand Judge",
        animeStyle: "kingdom",
        hairStyle: "Slicked back",
        hairColor: "#0a0a0a",
        eyeColor: "#03045e",
        skinTone: "#e6d5c3",
        outfit: "Judicial robes",
        outfitColors: ["#000000", "#ffd700"],
        accessories: ["Gavel", "Scales"],
        pose: "Judging",
        aura: "Purple authority",
        distinctiveFeature: "Stern gaze"
    },
    "analytical-creative": {
        archetype: "Mad Inventor",
        animeStyle: "one-piece",
        hairStyle: "Wild spiky",
        hairColor: "#ff9f1c",
        eyeColor: "#ff9f1c",
        skinTone: "#f8f5f0",
        outfit: "Lab coat with gears",
        outfitColors: ["#ffffff", "#ff9f1c"],
        accessories: ["Goggles", "Tools"],
        weapon: "Lightning gun",
        pose: "Excited invention",
        aura: "Electric sparks",
        distinctiveFeature: "Moving gadgets"
    },
    "analytical-stoic": {
        archetype: "Silent Observer",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Short neat",
        hairColor: "#5c4033",
        eyeColor: "#023e8a",
        skinTone: "#e8d5c4",
        outfit: "Dark tactical gear",
        outfitColors: ["#14213d", "#fca311"],
        accessories: ["Mask", "Cape"],
        weapon: "Hidden blades",
        pose: "In shadows",
        aura: "Blue mystery",
        distinctiveFeature: "Masked face"
    },
    "independent-traditional": {
        archetype: "Lone Samurai",
        animeStyle: "kingdom",
        hairStyle: "Tied back",
        hairColor: "#1c1c1c",
        eyeColor: "#fb8500",
        skinTone: "#d4a574",
        outfit: "Torn samurai armor",
        outfitColors: ["#212529", "#fb8500"],
        accessories: ["Katana", "Bandana"],
        weapon: "Katana",
        pose: "Battle stance",
        aura: "Orange spirit",
        distinctiveFeature: "X scar"
    },
    "independent-modern": {
        archetype: "Urban Rebel",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Punk mohawk",
        hairColor: "#ffb703",
        eyeColor: "#ffb703",
        skinTone: "#f5deb3",
        outfit: "Leather jacket",
        outfitColors: ["#000000", "#fb5607"],
        accessories: ["Chains", "Piercings"],
        weapon: "Metal bat",
        pose: "Rebellious",
        aura: "Fiery orange",
        distinctiveFeature: "Lightning tattoo"
    },
    "independent-casual": {
        archetype: "Nomadic Traveler",
        animeStyle: "one-piece",
        hairStyle: "Messy short",
        hairColor: "#964B00",
        eyeColor: "#8ecae6",
        skinTone: "#f0dcc4",
        outfit: "Traveler's cloak",
        outfitColors: ["#6f4e37", "#f4e5d3"],
        accessories: ["Backpack", "Map"],
        weapon: "Staff",
        pose: "Walking",
        aura: "Gentle breeze",
        distinctiveFeature: "Peaceful smile"
    },
    "independent-formal": {
        archetype: "Elite Commander",
        animeStyle: "kingdom",
        hairStyle: "Military cut",
        hairColor: "#4a4a4a",
        eyeColor: "#219ebc",
        skinTone: "#e8d5c0",
        outfit: "Military uniform",
        outfitColors: ["#023047", "#ffd700"],
        accessories: ["Cap", "Medals"],
        weapon: "Saber",
        pose: "Saluting",
        aura: "Blue authority",
        distinctiveFeature: "Eagle insignia"
    },
    "independent-creative": {
        archetype: "Revolutionary Artist",
        animeStyle: "mixed",
        hairStyle: "Asymmetrical",
        hairColor: "#e056fd",
        eyeColor: "#023047",
        skinTone: "#f5f5f5",
        outfit: "Paint-splattered",
        outfitColors: ["#e056fd", "#48cae4"],
        accessories: ["Beret", "Spray can"],
        pose: "Creating art",
        aura: "Multicolor",
        distinctiveFeature: "Paint on hands"
    },
    "independent-stoic": {
        archetype: "Silent Hermit",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Long unkempt",
        hairColor: "#3a3a3a",
        eyeColor: "#000000",
        skinTone: "#c4b5a0",
        outfit: "Tattered robes",
        outfitColors: ["#434343", "#6c6c6c"],
        accessories: ["Hood", "Beads"],
        pose: "Meditating",
        aura: "Dark void",
        distinctiveFeature: "Hidden face"
    },
    "altruistic-traditional": {
        archetype: "Holy Healer",
        animeStyle: "mixed",
        hairStyle: "Long white",
        hairColor: "#ffffff",
        eyeColor: "#7209b7",
        skinTone: "#ffe8e0",
        outfit: "Priest robes",
        outfitColors: ["#ffffff", "#ffd700"],
        accessories: ["Halo", "Book"],
        weapon: "Staff",
        pose: "Praying",
        aura: "Golden light",
        distinctiveFeature: "Glowing halo"
    },
    "altruistic-modern": {
        archetype: "Community Leader",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Friendly waves",
        hairColor: "#6d4c41",
        eyeColor: "#3a0ca3",
        skinTone: "#f4e8dc",
        outfit: "Volunteer vest",
        outfitColors: ["#4895ef", "#ffffff"],
        accessories: ["Badge", "Clipboard"],
        pose: "Waving",
        aura: "Warm yellow",
        distinctiveFeature: "Warm smile"
    },
    "altruistic-casual": {
        archetype: "Friendly Helper",
        animeStyle: "one-piece",
        hairStyle: "Curly short",
        hairColor: "#8b7355",
        eyeColor: "#4361ee",
        skinTone: "#f5deb3",
        outfit: "Comfy sweater",
        outfitColors: ["#ffb4a2", "#e5989b"],
        accessories: ["Apron", "Bandana"],
        pose: "Helping hand",
        aura: "Pink hearts",
        distinctiveFeature: "Band-aid"
    },
    "altruistic-formal": {
        archetype: "Dignified Diplomat",
        animeStyle: "kingdom",
        hairStyle: "Elegant long",
        hairColor: "#f0e68c",
        eyeColor: "#4cc9f0",
        skinTone: "#fff5ee",
        outfit: "Diplomatic robes",
        outfitColors: ["#ffffff", "#4cc9f0"],
        accessories: ["Pearls", "Gloves"],
        pose: "Curtsy",
        aura: "White light",
        distinctiveFeature: "Grace"
    },
    "altruistic-creative": {
        archetype: "Hope Bringer",
        animeStyle: "mixed",
        hairStyle: "Braided flowers",
        hairColor: "#ff69b4",
        eyeColor: "#f72585",
        skinTone: "#ffe0e5",
        outfit: "Performer outfit",
        outfitColors: ["#ff006e", "#ffbe0b"],
        accessories: ["Flower crown", "Ribbons"],
        pose: "Dancing",
        aura: "Rainbow butterflies",
        distinctiveFeature: "Blooming flowers"
    },
    "altruistic-stoic": {
        archetype: "Steadfast Guardian",
        animeStyle: "kingdom",
        hairStyle: "Military buzz",
        hairColor: "#696969",
        eyeColor: "#b5179e",
        skinTone: "#d4a88c",
        outfit: "Heavy armor",
        outfitColors: ["#5a189a", "#c77dff"],
        accessories: ["Shield", "Gauntlets"],
        weapon: "Shield & Mace",
        pose: "Guard stance",
        aura: "Purple barrier",
        distinctiveFeature: "Determined eyes"
    },
    "enigmatic-traditional": {
        archetype: "Mysterious Oracle",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Long black",
        hairColor: "#0a0a0a",
        eyeColor: "#9d4edd",
        skinTone: "#f0e8e0",
        outfit: "Occult robes",
        outfitColors: ["#10002b", "#7209b7"],
        accessories: ["Veil", "Crystal ball"],
        weapon: "Cursed dagger",
        pose: "Reading future",
        aura: "Purple smoke",
        distinctiveFeature: "Third eye"
    },
    "enigmatic-modern": {
        archetype: "Shadow Manipulator",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Split black/white",
        hairColor: "#000000",
        eyeColor: "#5a189a",
        skinTone: "#e8e0d8",
        outfit: "Dark suit",
        outfitColors: ["#1a1a1a", "#5a189a"],
        accessories: ["Mask", "Rings"],
        weapon: "Shadow blade",
        pose: "From shadows",
        aura: "Dual light/dark",
        distinctiveFeature: "Phase shifting"
    },
    "enigmatic-casual": {
        archetype: "Playful Trickster",
        animeStyle: "one-piece",
        hairStyle: "Fox-like spiky",
        hairColor: "#ff7f00",
        eyeColor: "#fb8500",
        skinTone: "#f5d5a8",
        outfit: "Fox kimono",
        outfitColors: ["#fb8500", "#ffb703"],
        accessories: ["Fox mask", "Tail"],
        weapon: "Trick fan",
        pose: "Mischievous",
        aura: "Fox fire",
        distinctiveFeature: "Fox features"
    },
    "enigmatic-formal": {
        archetype: "Ice Sovereign",
        animeStyle: "kingdom",
        hairStyle: "Long icy blue",
        hairColor: "#b8d8e8",
        eyeColor: "#3c096c",
        skinTone: "#f0f8ff",
        outfit: "Ice armor",
        outfitColors: ["#caf0f8", "#0077b6"],
        accessories: ["Ice crown", "Frost cape"],
        weapon: "Ice scepter",
        pose: "Commanding",
        aura: "Freezing mist",
        distinctiveFeature: "Frost breath"
    },
    "enigmatic-creative": {
        archetype: "Shapeshifter",
        animeStyle: "mixed",
        hairStyle: "Fluid changing",
        hairColor: "#52b788",
        eyeColor: "#1a7431",
        skinTone: "#d4f1d4",
        outfit: "Morphing garments",
        outfitColors: ["#52b788", "#95d5b2"],
        accessories: ["Morphing mask"],
        weapon: "Shapeshifting staff",
        pose: "Transforming",
        aura: "Green energy",
        distinctiveFeature: "Rippling body"
    },
    "enigmatic-stoic": {
        archetype: "Shadowed Watcher",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Hidden hood",
        hairColor: "#2d2d2d",
        eyeColor: "#240046",
        skinTone: "#a8a8a8",
        outfit: "Concealing robes",
        outfitColors: ["#0d0d0d", "#240046"],
        accessories: ["Blindfold", "Chains"],
        pose: "Motionless",
        aura: "Void darkness",
        distinctiveFeature: "Hidden features"
    },
    "vibrant-traditional": {
        archetype: "Golden Leader",
        animeStyle: "kingdom",
        hairStyle: "Radiant spiky",
        hairColor: "#ffd700",
        eyeColor: "#fbbf24",
        skinTone: "#f4d5a8",
        outfit: "Golden armor",
        outfitColors: ["#ffd700", "#ff6b35"],
        accessories: ["Crown", "Belt"],
        weapon: "Golden spear",
        pose: "Victory",
        aura: "Golden radiance",
        distinctiveFeature: "Constant shine"
    },
    "vibrant-modern": {
        archetype: "Pop Icon",
        animeStyle: "mixed",
        hairStyle: "Trendy colorful",
        hairColor: "#ff1744",
        eyeColor: "#e11d48",
        skinTone: "#ffe8e0",
        outfit: "Stage outfit",
        outfitColors: ["#ff1744", "#00bcd4"],
        accessories: ["Microphone", "Headphones"],
        pose: "Performing",
        aura: "Spotlights",
        distinctiveFeature: "Star pupils"
    },
    "vibrant-casual": {
        archetype: "Energetic Adventurer",
        animeStyle: "one-piece",
        hairStyle: "Wild spiky",
        hairColor: "#1a1a1a",
        eyeColor: "#10b981",
        skinTone: "#f5c894",
        outfit: "Adventure gear",
        outfitColors: ["#dc2626", "#3b82f6"],
        accessories: ["Straw hat", "Goggles"],
        pose: "Running forward",
        aura: "Green energy",
        distinctiveFeature: "Wide grin"
    },
    "vibrant-formal": {
        archetype: "Grand Noble",
        animeStyle: "kingdom",
        hairStyle: "Elaborate styled",
        hairColor: "#8b0000",
        eyeColor: "#dc2626",
        skinTone: "#ffe0d8",
        outfit: "Extravagant noble attire",
        outfitColors: ["#dc2626", "#ffd700"],
        accessories: ["Jeweled crown", "Fan"],
        weapon: "Rapier",
        pose: "On throne",
        aura: "Crimson flames",
        distinctiveFeature: "Peacock motif"
    },
    "vibrant-creative": {
        archetype: "Brilliant Innovator",
        animeStyle: "mixed",
        hairStyle: "Glowing fiery",
        hairColor: "#ff6600",
        eyeColor: "#ea580c",
        skinTone: "#f8e8d8",
        outfit: "Tech creative outfit",
        outfitColors: ["#fb8500", "#ffba08"],
        accessories: ["Lightbulb pendant", "Goggles"],
        weapon: "Energy cannon",
        pose: "Eureka moment",
        aura: "Electric orange",
        distinctiveFeature: "Hair on fire"
    },
    "vibrant-stoic": {
        archetype: "Weathered Explorer",
        animeStyle: "one-piece",
        hairStyle: "Short rugged",
        hairColor: "#808080",
        eyeColor: "#44403c",
        skinTone: "#d4a88c",
        outfit: "Explorer gear",
        outfitColors: ["#78716c", "#44403c"],
        accessories: ["Backpack", "Compass"],
        weapon: "Pickaxe",
        pose: "Climbing",
        aura: "Earth determination",
        distinctiveFeature: "Map tattoos"
    }
};
