// Anime-style character design metadata
type CharacterDesign = {
    archetype: string;
    animeStyle: "one-piece" | "kingdom" | "jujutsu-kaisen" | "mixed";
    hairStyle: string;
    hairColor: string;
    eyeColor: string;
    skinTone: string;
    outfit: string;
    outfitColors: string[];
    accessories: string[];
    weapon?: string;
    pose: string;
    aura: string;
    distinctiveFeature: string;
};

export const CHARACTER_DESIGNS: Record<string, CharacterDesign> = {
    "romantic-traditional": {
        archetype: "Noble Knight",
        animeStyle: "kingdom",
        hairStyle: "Geometric long silver",
        hairColor: "#e8e8e8",
        eyeColor: "#333",
        skinTone: "#ffd5cd",
        outfit: "Crimson tabard",
        outfitColors: ["#c1121f", "#ffffff"],
        accessories: ["Shield", "Banner"],
        weapon: "Longsword",
        pose: "Dignified stand",
        aura: "None",
        distinctiveFeature: "Plumed helmet"
    },
    "romantic-modern": {
        archetype: "Urban Romantic",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Geometric bob",
        hairColor: "#4a4a4a",
        eyeColor: "#333",
        skinTone: "#f8e8dc",
        outfit: "Modern suit",
        outfitColors: ["#1a1a2e", "#e94b3c"],
        accessories: ["Watch", "Smartphone"],
        pose: "Casual lean",
        aura: "None",
        distinctiveFeature: "Stylish glasses"
    },
    "romantic-casual": {
        archetype: "Wandering Poet",
        animeStyle: "one-piece",
        hairStyle: "Messy geometric hair",
        hairColor: "#8b4513",
        eyeColor: "#333",
        skinTone: "#f5d5c0",
        outfit: "Artist shirt",
        outfitColors: ["#f8f9fa", "#495057"],
        accessories: ["Pen", "Journal"],
        pose: "Writing posture",
        aura: "None",
        distinctiveFeature: "Ink marks"
    },
    "romantic-formal": {
        archetype: "Royal Suitor",
        animeStyle: "kingdom",
        hairStyle: "Elegant geometric updo",
        hairColor: "#2c1810",
        eyeColor: "#333",
        skinTone: "#ffe5d9",
        outfit: "Ceremonial robes",
        outfitColors: ["#8b0000", "#ffd700"],
        accessories: ["Fan", "Crest"],
        weapon: "Ceremonial blade",
        pose: "Graceful stand",
        aura: "None",
        distinctiveFeature: "Gold embroidery"
    },
    "romantic-creative": {
        archetype: "Dream Weaver",
        animeStyle: "mixed",
        hairStyle: "Angular long hair",
        hairColor: "#ff69b4",
        eyeColor: "#333",
        skinTone: "#f0e5e5",
        outfit: "Artist robes",
        outfitColors: ["#e0aaff", "#ff99c8"],
        accessories: ["Flower", "Star wand"],
        weapon: "Magic brush",
        pose: "Floating",
        aura: "None",
        distinctiveFeature: "Star motifs"
    },
    "romantic-stoic": {
        archetype: "Lone Warrior",
        animeStyle: "kingdom",
        hairStyle: "Short blocky hair",
        hairColor: "#1a1a1a",
        eyeColor: "#333",
        skinTone: "#d4a574",
        outfit: "Tattered armor",
        outfitColors: ["#2b2d42", "#d00000"],
        accessories: ["Scarf", "Badge"],
        weapon: "Greatsword",
        pose: "Determined stand",
        aura: "None",
        distinctiveFeature: "Battle scar"
    },
    "analytical-traditional": {
        archetype: "Ancient Scholar",
        animeStyle: "kingdom",
        hairStyle: "Chunky white hair",
        hairColor: "#f0f0f0",
        eyeColor: "#333",
        skinTone: "#ddc8ad",
        outfit: "Sage robes",
        outfitColors: ["#774936", "#e8dcc4"],
        accessories: ["Scrolls", "Glasses"],
        weapon: "Magic staff",
        pose: "Holding staff",
        aura: "None",
        distinctiveFeature: "Long beard"
    },
    "analytical-modern": {
        archetype: "Tech Strategist",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Angular slicked back",
        hairColor: "#c0c0c0",
        eyeColor: "#333",
        skinTone: "#f5f5f5",
        outfit: "Tactical gear",
        outfitColors: ["#023e8a", "#00f5ff"],
        accessories: ["Blueprints", "Tablet"],
        weapon: "Energy blade",
        pose: "Planning",
        aura: "None",
        distinctiveFeature: "Cyber lens"
    },
    "analytical-casual": {
        archetype: "Detective",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Messy blocky hair",
        hairColor: "#2d2d2d",
        eyeColor: "#333",
        skinTone: "#ede0d4",
        outfit: "Trench coat",
        outfitColors: ["#6c757d", "#ffffff"],
        accessories: ["Magnifying glass", "Notebook"],
        pose: "Observing",
        aura: "None",
        distinctiveFeature: "Thinking face"
    },
    "analytical-formal": {
        archetype: "Grand Judge",
        animeStyle: "kingdom",
        hairStyle: "Neat geometric cut",
        hairColor: "#0a0a0a",
        eyeColor: "#333",
        skinTone: "#e6d5c3",
        outfit: "High court robes",
        outfitColors: ["#000000", "#ffd700"],
        accessories: ["Gavel", "Scales of justice"],
        pose: "Judgment",
        aura: "None",
        distinctiveFeature: "Stern gaze"
    },
    "analytical-creative": {
        archetype: "Mad Inventor",
        animeStyle: "one-piece",
        hairStyle: "Low-poly spiky hair",
        hairColor: "#ff9f1c",
        eyeColor: "#333",
        skinTone: "#f8f5f0",
        outfit: "Lab coat",
        outfitColors: ["#ffffff", "#ff9f1c"],
        accessories: ["Wrench", "Goggles"],
        weapon: "Gadget",
        pose: "Holding wrench",
        aura: "None",
        distinctiveFeature: "Oil stains"
    },
    "analytical-stoic": {
        archetype: "Silent Observer",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Short geometric",
        hairColor: "#5c4033",
        eyeColor: "#333",
        skinTone: "#e8d5c4",
        outfit: "Dark minimalist gear",
        outfitColors: ["#14213d", "#fca311"],
        accessories: ["Mask", "Binoculars"],
        weapon: "None",
        pose: "Standing still",
        aura: "None",
        distinctiveFeature: "Hidden eyes"
    },
    "independent-traditional": {
        archetype: "Lone Samurai",
        animeStyle: "kingdom",
        hairStyle: "Topknot geometric",
        hairColor: "#1c1c1c",
        eyeColor: "#333",
        skinTone: "#d4a574",
        outfit: "Wanderer's kimono",
        outfitColors: ["#212529", "#fb8500"],
        accessories: ["Katana", "Bandana"],
        weapon: "Katana",
        pose: "Action pose",
        aura: "None",
        distinctiveFeature: "Rugged look"
    },
    "independent-modern": {
        archetype: "Urban Rebel",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Cubic mohawk",
        hairColor: "#ffb703",
        eyeColor: "#333",
        skinTone: "#f5deb3",
        outfit: "Rebel jacket",
        outfitColors: ["#000000", "#fb5607"],
        accessories: ["Speaker", "Spray can"],
        weapon: "Art batch",
        pose: "Rebel stance",
        aura: "None",
        distinctiveFeature: "Bolt tattoo"
    },
    "independent-casual": {
        archetype: "Nomadic Traveler",
        animeStyle: "one-piece",
        hairStyle: "Shaggy geometric",
        hairColor: "#964B00",
        eyeColor: "#333",
        skinTone: "#f0dcc4",
        outfit: "Traveler poncho",
        outfitColors: ["#6f4e37", "#f4e5d3"],
        accessories: ["Backpack", "Compass"],
        weapon: "Walking staff",
        pose: "Walking",
        aura: "None",
        distinctiveFeature: "Traveler's hat"
    },
    "independent-formal": {
        archetype: "Elite Commander",
        animeStyle: "kingdom",
        hairStyle: "Sharp military cut",
        hairColor: "#4a4a4a",
        eyeColor: "#333",
        skinTone: "#e8d5c0",
        outfit: "Commanding uniform",
        outfitColors: ["#023047", "#ffd700"],
        accessories: ["Map", "Medals"],
        weapon: "Commander sword",
        pose: "Giving orders",
        aura: "None",
        distinctiveFeature: "Sharp gaze"
    },
    "independent-creative": {
        archetype: "Revolutionary Artist",
        animeStyle: "mixed",
        hairStyle: "Asymmetrical geometric",
        hairColor: "#e056fd",
        eyeColor: "#333",
        skinTone: "#f5f5f5",
        outfit: "Artistic gear",
        outfitColors: ["#e056fd", "#48cae4"],
        accessories: ["Palette", "Canvas"],
        pose: "Painting",
        aura: "None",
        distinctiveFeature: "Paint splatters"
    },
    "independent-stoic": {
        archetype: "Silent Hermit",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Long blocky",
        hairColor: "#3a3a3a",
        eyeColor: "#333",
        skinTone: "#c4b5a0",
        outfit: "Rough robes",
        outfitColors: ["#434343", "#6c6c6c"],
        accessories: ["Staff", "Hood"],
        pose: "Meditating",
        aura: "None",
        distinctiveFeature: "Hidden face"
    },
    "altruistic-traditional": {
        archetype: "Holy Healer",
        animeStyle: "mixed",
        hairStyle: "Geometric long mane",
        hairColor: "#ffffff",
        eyeColor: "#333",
        skinTone: "#ffe8e0",
        outfit: "Sacred vestments",
        outfitColors: ["#ffffff", "#ffd700"],
        accessories: ["Censer", "Holy book"],
        weapon: "Healing staff",
        pose: "Blessing",
        aura: "None",
        distinctiveFeature: "Light aura"
    },
    "altruistic-modern": {
        archetype: "Community Leader",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Friendly blocky waves",
        hairColor: "#6d4c41",
        eyeColor: "#333",
        skinTone: "#f4e8dc",
        outfit: "Civic uniform",
        outfitColors: ["#4895ef", "#ffffff"],
        accessories: ["Megaphone", "Clipboard"],
        pose: "Organizing",
        aura: "None",
        distinctiveFeature: "Wide smile"
    },
    "altruistic-casual": {
        archetype: "Friendly Helper",
        animeStyle: "one-piece",
        hairStyle: "Curly geometric",
        hairColor: "#8b7355",
        eyeColor: "#333",
        skinTone: "#f5deb3",
        outfit: "Hospitality apron",
        outfitColors: ["#ffb4a2", "#e5989b"],
        accessories: ["Tray", "Badge"],
        pose: "Serving",
        aura: "None",
        distinctiveFeature: "Warm eyes"
    },
    "altruistic-formal": {
        archetype: "Dignified Diplomat",
        animeStyle: "kingdom",
        hairStyle: "Elegant long blocky",
        hairColor: "#f0e68c",
        eyeColor: "#333",
        skinTone: "#fff5ee",
        outfit: "Consul robes",
        outfitColors: ["#ffffff", "#4cc9f0"],
        accessories: ["Cake", "Umbrella"],
        pose: "Negotiating",
        aura: "None",
        distinctiveFeature: "Poise"
    },
    "altruistic-creative": {
        archetype: "Hope Bringer",
        animeStyle: "mixed",
        hairStyle: "Angular floral braids",
        hairColor: "#ff69b4",
        eyeColor: "#333",
        skinTone: "#ffe0e5",
        outfit: "Messenger outfit",
        outfitColors: ["#ff006e", "#ffbe0b"],
        accessories: ["Satchel", "Flowers"],
        pose: "Delivering hope",
        aura: "None",
        distinctiveFeature: "Ribbons"
    },
    "altruistic-stoic": {
        archetype: "Steadfast Guardian",
        animeStyle: "kingdom",
        hairStyle: "Blocky buzz cut",
        hairColor: "#696969",
        eyeColor: "#333",
        skinTone: "#d4a88c",
        outfit: "Sentinel armor",
        outfitColors: ["#5a189a", "#c77dff"],
        accessories: ["Tower shield", "Torch"],
        weapon: "Shield",
        pose: "Guarding",
        aura: "None",
        distinctiveFeature: "Steadfast gaze"
    },
    "enigmatic-traditional": {
        archetype: "Mysterious Oracle",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Long geometric black",
        hairColor: "#0a0a0a",
        eyeColor: "#333",
        skinTone: "#f0e8e0",
        outfit: "Mystic robes",
        outfitColors: ["#10002b", "#7209b7"],
        accessories: ["Crystal ball", "Tarot cards"],
        weapon: "Oracle staff",
        pose: "Scrying",
        aura: "None",
        distinctiveFeature: "Veil"
    },
    "enigmatic-modern": {
        archetype: "Shadow Manipulator",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Geometric split hair",
        hairColor: "#000000",
        eyeColor: "#333",
        skinTone: "#e8e0d8",
        outfit: "High-tech noir suit",
        outfitColors: ["#1a1a1a", "#5a189a"],
        accessories: ["Hologram", "Tablet"],
        weapon: "None",
        pose: "Fading into shadows",
        aura: "None",
        distinctiveFeature: "Dual-tone look"
    },
    "enigmatic-casual": {
        archetype: "Playful Trickster",
        animeStyle: "one-piece",
        hairStyle: "Fox-shaped geometric",
        hairColor: "#ff7f00",
        eyeColor: "#333",
        skinTone: "#f5d5a8",
        outfit: "Trickster vest",
        outfitColors: ["#fb8500", "#ffb703"],
        accessories: ["Mask", "Cards"],
        weapon: "Fan",
        pose: "Joking",
        aura: "None",
        distinctiveFeature: "Mischief"
    },
    "enigmatic-formal": {
        archetype: "Ice Sovereign",
        animeStyle: "kingdom",
        hairStyle: "Sharp frozen spikes",
        hairColor: "#b8d8e8",
        eyeColor: "#333",
        skinTone: "#f0f8ff",
        outfit: "Glacial mantle",
        outfitColors: ["#caf0f8", "#0077b6"],
        accessories: ["Scepter", "Orb"],
        weapon: "Ice wand",
        pose: "Ruling",
        aura: "None",
        distinctiveFeature: "Frost crown"
    },
    "enigmatic-creative": {
        archetype: "Shapeshifter",
        animeStyle: "mixed",
        hairStyle: "Fluid polygons",
        hairColor: "#52b788",
        eyeColor: "#333",
        skinTone: "#d4f1d4",
        outfit: "Liquid-metal robes",
        outfitColors: ["#52b788", "#95d5b2"],
        accessories: ["Relic", "Mirror"],
        pose: "Shifting",
        aura: "None",
        distinctiveFeature: "Green glow"
    },
    "enigmatic-stoic": {
        archetype: "Shadowed Watcher",
        animeStyle: "jujutsu-kaisen",
        hairStyle: "Hidden blocky hood",
        hairColor: "#2d2d2d",
        eyeColor: "#333",
        skinTone: "#a8a8a8",
        outfit: "Silent cloak",
        outfitColors: ["#0d0d0d", "#240046"],
        accessories: ["Lantern", "Key"],
        pose: "Watching",
        aura: "None",
        distinctiveFeature: "Covered face"
    },
    "vibrant-traditional": {
        archetype: "Golden Leader",
        animeStyle: "kingdom",
        hairStyle: "Cubic radiant hair",
        hairColor: "#ffd700",
        eyeColor: "#333",
        skinTone: "#f4d5a8",
        outfit: "Golden cuirass",
        outfitColors: ["#ffd700", "#ff6b35"],
        accessories: ["Staff of Light", "Standard"],
        weapon: "Scepter",
        pose: "Leading",
        aura: "None",
        distinctiveFeature: "Sun emblem"
    },
    "vibrant-modern": {
        archetype: "Pop Icon",
        animeStyle: "mixed",
        hairStyle: "Neon geometric spikes",
        hairColor: "#ff1744",
        eyeColor: "#333",
        skinTone: "#ffe8e0",
        outfit: "Cyber-pop outfit",
        outfitColors: ["#ff1744", "#00bcd4"],
        accessories: ["Microphone", "Speakers"],
        pose: "Performing",
        aura: "None",
        distinctiveFeature: "Star shades"
    },
    "vibrant-casual": {
        archetype: "Energetic Adventurer",
        animeStyle: "one-piece",
        hairStyle: "Wild cubic hair",
        hairColor: "#1a1a1a",
        eyeColor: "#333",
        skinTone: "#f5c894",
        outfit: "Explorer vest",
        outfitColors: ["#dc2626", "#3b82f6"],
        accessories: ["Pickaxe", "Flint"],
        weapon: "Explorer kit",
        pose: "Running",
        aura: "None",
        distinctiveFeature: "Broad grin"
    },
    "vibrant-formal": {
        archetype: "Grand Noble",
        animeStyle: "kingdom",
        hairStyle: "Ornate geometric peruke",
        hairColor: "#8b0000",
        eyeColor: "#333",
        skinTone: "#ffe0d8",
        outfit: "Extravagant suit",
        outfitColors: ["#dc2626", "#ffd700"],
        accessories: ["Medallion", "Cane"],
        weapon: "Gold-plated sword",
        pose: "Elegant stand",
        aura: "None",
        distinctiveFeature: "Grand cape"
    },
    "vibrant-creative": {
        archetype: "Brilliant Innovator",
        animeStyle: "mixed",
        hairStyle: "Fiery geometric mane",
        hairColor: "#ff6600",
        eyeColor: "#333",
        skinTone: "#f8e8d8",
        outfit: "Inventor's smock",
        outfitColors: ["#fb8500", "#ffba08"],
        accessories: ["Alembic", "Blueprints"],
        pose: "Eureka pose",
        aura: "None",
        distinctiveFeature: "Glowing eyes"
    },
    "vibrant-stoic": {
        archetype: "Weathered Explorer",
        animeStyle: "one-piece",
        hairStyle: "Rugged blocky cut",
        hairColor: "#808080",
        eyeColor: "#333",
        skinTone: "#d4a88c",
        outfit: "Outdoor gear",
        outfitColors: ["#78716c", "#44403c"],
        accessories: ["Lantern", "Pickaxe"],
        weapon: "Hammer",
        pose: "Hiking",
        aura: "None",
        distinctiveFeature: "Tattoos"
    }
};
